version: "3"

services:
  app:
    build: .docker
    hostname: app
    command: ["yarn", "dev"]
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
    environment:
      DATABASE_URL: "sqlite:database.sqlite"
